# embed_font.ps1 - linear-time TrueType byte-array emitter for lsxhome.
#
# Reads the input TTF and writes a C++ translation unit whose array exposes the
# payload from static memory (.rdata on PE32+), plus the sibling header defining
# the size as an inline constexpr (so static_assert/STATIC_REQUIRE can consume
# it at compile time). This runs at CMake configure time via lsx_embed_binary().
#
# Linear fast path: .NET byte arrays + a StringBuilder - no quadratic regex on
# huge hex strings, which was stalling the configure step for minutes.

param(
    [Parameter(Mandatory = $true)][string]$InputFile,
    [Parameter(Mandatory = $true)][string]$Symbol,
    [Parameter(Mandatory = $true)][string]$OutCpp
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $InputFile)) {
    throw "embed_font.ps1: input file not found: $InputFile"
}

$bytes = [System.IO.File]::ReadAllBytes($InputFile)
$byteCount = $bytes.Length

$sb = [System.Text.StringBuilder]::new(($byteCount * 6) + 1024)
[void]$sb.AppendLine('const std::uint8_t ' + $Symbol + '[] = {')
for ($i = 0; $i -lt $byteCount; $i++) {
    [void]$sb.Append('0x' + $bytes[$i].ToString('X2') + 'U, ')
    if (($i + 1) % 12 -eq 0) {
        [void]$sb.AppendLine()
    }
}
if ($byteCount % 12 -ne 0) {
    [void]$sb.AppendLine()
}
[void]$sb.AppendLine('};')

$OutHeader = [System.IO.Path]::ChangeExtension($OutCpp, '.h')
$HeaderName = [System.IO.Path]::GetFileName($OutHeader)
$CppName = [System.IO.Path]::GetFileName($OutCpp)

$header = @"
// Autogenerated by lsx_embed_binary.cmake - do not edit.
// Payload: $((Get-Item -LiteralPath $InputFile).FullName) ($byteCount bytes) - static execution memory.
#pragma once
#include <cstddef>
#include <cstdint>
extern const std::uint8_t $Symbol[];
inline constexpr std::size_t ${Symbol}_size = $byteCount;
"@

$cpp = @"
// Autogenerated by lsx_embed_binary.cmake - do not edit.
#include "$HeaderName"
$($sb.ToString())
"@

# UTF-8 no BOM - MSVC/cl and GCC both accept it; keeps diffs clean.
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutCpp, $cpp, $utf8NoBom)
[System.IO.File]::WriteAllText($OutHeader, $header, $utf8NoBom)

Write-Output "embed_font.ps1: $InputFile -> $OutCpp ($byteCount bytes, symbol $Symbol)"