# lsx_embed_binary - bake a binary file into a C++ byte array at configure time.
#
#   lsx_embed_binary(<input-file> <symbol> <output-cpp>)
#
# The heavy lifting is delegated to embed_font.ps1 (linear byte stream, ~100 ms
# for a 400 KB TTF) because string(REGEX)/loop tricks in CMake's script engine
# are O(n^2) on multi-megabyte hex strings and stall the configure step for many
# minutes. The generated unit owns the payload in the linker's static data
# (.rdata on PE32+); the lsxhome resource loader reads the TrueType vector
# straight out of that pre-allocated static memory - no heap copy at startup.

function(lsx_embed_binary INPUT_FILE SYMBOL OUTPUT_CPP)
    if(NOT EXISTS "${INPUT_FILE}")
        message(FATAL_ERROR "lsx_embed_binary: input file not found: ${INPUT_FILE}")
    endif()

    # Path is relative to THIS function's definition file (embed_binary.cmake),
    # NOT to the calling CMakeLists.txt.
    set(SCRIPT_PATH "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/embed_font.ps1")

    # PowerShell is the native Windows shell for this project (win32-only block).
    # Use it for the byte stream; keep the CMake fallback for non-Windows hosts
    # where lsxhome is never built anyway (guarded by the WIN32 early return).
    if(CMAKE_HOST_WIN32)
        find_program(LSXHOME_EMBED_PWSH NAMES pwsh powershell)
        if(LSXHOME_EMBED_PWSH)
            execute_process(
                COMMAND "${LSXHOME_EMBED_PWSH}" -NoProfile -ExecutionPolicy Bypass
                        -File "${SCRIPT_PATH}"
                        -InputFile "${INPUT_FILE}"
                        -Symbol "${SYMBOL}"
                        -OutCpp "${OUTPUT_CPP}"
                RESULT_VARIABLE LSXHOME_EMBED_RESULT
                OUTPUT_VARIABLE LSXHOME_EMBED_OUT
                ERROR_VARIABLE  LSXHOME_EMBED_ERR
            )
            if(NOT LSXHOME_EMBED_RESULT EQUAL 0)
                message(FATAL_ERROR
                    "lsx_embed_binary: ps1 generation failed (${LSXHOME_EMBED_RESULT}) "
                    "for ${INPUT_FILE}: ${LSXHOME_EMBED_OUT} ${LSXHOME_EMBED_ERR}")
            endif()
            return()
        endif()
    endif()

    # Fallback: plain-CMake emitter (slow, kept only for non-Windows dev sanity).
    file(SIZE "${INPUT_FILE}" BYTE_SIZE)
    file(READ "${INPUT_FILE}" HEX_BYTES HEX)
    set(PAIRS "")
    string(LENGTH "${HEX_BYTES}" HEX_LEN)
    set(I 0)
    while(I LESS HEX_LEN)
        string(SUBSTRING "${HEX_BYTES}" ${I} 2 BYTE_HEX)
        string(APPEND PAIRS "0x${BYTE_HEX}U, ")
        math(EXPR I "${I} + 2")
    endwhile()

    get_filename_component(OUTPUT_CPP_FILENAME "${OUTPUT_CPP}" NAME)
    string(REPLACE ".cpp" ".h" OUTPUT_HDR "${OUTPUT_CPP}")
    get_filename_component(OUTPUT_HDR_FILENAME "${OUTPUT_HDR}" NAME)

    set(GEN_HDR
"// Autogenerated by lsx_embed_binary.cmake - do not edit.
// Payload: ${INPUT_FILE} (${BYTE_SIZE} bytes) - static execution memory.
#pragma once
#include <cstddef>
#include <cstdint>
extern const std::uint8_t ${SYMBOL}[];
inline constexpr std::size_t ${SYMBOL}_size = ${BYTE_SIZE};
")
    set(GEN_BODY
"// Autogenerated by lsx_embed_binary.cmake - do not edit.
#include \"${OUTPUT_HDR_FILENAME}\"
const std::uint8_t ${SYMBOL}[] = {
${PAIRS}
};
")
    file(WRITE "${OUTPUT_HDR}" "${GEN_HDR}")
    file(WRITE "${OUTPUT_CPP}" "${GEN_BODY}")
endfunction()